# Generated by Django 4.1.5 on 2023-04-14 14:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0009_delete_document'),
        ('employees', '0012_alter_employee_firstname_alter_employee_surname'),
        ('docs', '0003_remove_doc_citizenship_doc_date_of_preparing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='doc',
            name='current_status',
            field=models.CharField(choices=[('active', 'Действующий'), ('inactive', 'Архив')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='doc',
            name='date_of_expiry',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='doc',
            name='date_of_issue',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='doc',
            name='date_of_preparing',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='doc',
            name='doc_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.documenttype'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='issued_authority',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='doc',
            name='number',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='doc',
            name='others',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='doc',
            name='scanned_doc',
            field=models.FileField(blank=True, upload_to='docs/uploads/'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='serial',
            field=models.CharField(max_length=200),
        ),
    ]
