# Generated by Django 4.1.5 on 2023-04-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_alter_employee_address_alter_employee_citizenship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='firstname',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='surname',
            field=models.CharField(max_length=200),
        ),
    ]
